# Generated by Django 4.0.7 on 2023-07-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('published_date', models.DateField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
