# Generated by Django 4.0.7 on 2023-07-05 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='copy',
        ),
    ]
