# Generated by Django 4.0.7 on 2023-07-05 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copies', '0003_alter_copies_unique_together'),
        ('loans', '0002_remove_loan_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='copy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='copies.copies'),
            preserve_default=False,
        ),
    ]
