# Generated by Django 4.0.7 on 2023-07-05 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('copies', '0005_alter_copies_unique_together'),
        ('loans', '0003_loan_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='copies.copies'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
