# Generated by Django 4.0.7 on 2023-07-06 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0005_loan_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='returned',
        ),
    ]
