# Generated by Django 4.0.7 on 2023-07-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_loan_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='return_made',
            field=models.DateField(blank=True, null=True),
        ),
    ]
