# Generated by Django 4.0.7 on 2023-07-05 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_published_date'),
        ('copies', '0002_copies_delete_copy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='copies',
            unique_together={('book',)},
        ),
    ]
