# Generated by Django 4.0.7 on 2023-07-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copies', '0004_alter_copies_available_alter_copies_total'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='copies',
            unique_together=set(),
        ),
    ]
