# Generated by Django 4.0.7 on 2023-07-06 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_published_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copies', '0005_alter_copies_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
